version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mapa-dna-frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mapa-dna-backend
    restart: unless-stopped
    environment:
      - PORT=3002
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBHOOK_URL=https://wbn.araxa.app/webhook/mapa-dna-financeiro
      - CORS_ORIGIN=https://www.lp.mapadnafinanceiro.com
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: mapa-dna-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
