version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mapadna-frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --head http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mapadna-backend
    restart: always
    ports:
      - "3002:3002"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - PORT=3002
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: mapadna-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --head http://127.0.0.1/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge
